use_frameworks!

target 'SwinjectAutoregistration_Example' do
  pod 'SwinjectAutoregistration', :path => '../'

  target 'SwinjectAutoregistration_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 0.8'
  pod 'Nimble', '~> 3.0'
  end
end
